@hostname = http://127.0.0.1:5000/api/v1/lone-payments
@token = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidG9rZW4iOiI3Y3B5Njk5ayIsImlhdCI6MTcxNTU5MzI4OX0.m93Huq4TS1EtEPp2bee2lOlLyqvJ7TWE-Sg4eAhA51U

# all
###
GET {{hostname}} HTTP/1.1

# get
###
GET {{hostname}}/1 HTTP/1.1

# store
###
POST  {{hostname}}/store HTTP/1.1
content-type: application/json
Authorization: {{token}}

{
    "branch_id": 1,
    "lone_id": 1,
    "date": "10-10-2025",
    "amount": 12000,
    "next_payment_date": "10-10-2025",
    "rest_amount": 12000,
    "paid_amount": 12000,
    "received_by": "mozammel hossain",
    "account_log_id": 1
}


# update
###
POST {{hostname}}/update HTTP/1.1 
content-type: application/json
Authorization: {{token}}

{
    "id": 2,
    "branch_id": 2,
    "lone_id": 2,
    "date": "10-10-2025",
    "amount": 12000,
    "next_payment_date": "10-10-2025",
    "rest_amount": 12000,
    "paid_amount": 12000,
    "received_by": "mozammel hossain",
    "account_log_id": 2
}

# delete
###
POST  {{hostname}}/soft-delete HTTP/1.1
content-type: application/json

{
    "id": 2
}

# restore
###
POST  {{hostname}}/restore HTTP/1.1
content-type: application/json

{
    "id": 2
}


# destroy
###
POST  {{hostname}}/destroy HTTP/1.1
content-type: application/json

{
    "id": 2
}